import { mkdir, open, rm } from 'node:fs/promises';
import path from 'node:path';
import { AUX, hasErrorCode } from '../shared/core.js';
import { atomicJson, atomicWrite, exists } from './files.js';
import type { JsonObject } from '../shared/types.js';

export { AUX } from '../shared/core.js';

/** Absolute path to a file or directory inside the project's `.qmd-prover/` state directory. */
export function auxPath(root: string, ...segments: string[]): string {
  return path.join(root, AUX, ...segments);
}

function bare(digest: string): string {
  return digest.replace(/^sha256:/, '');
}

/**
 * The on-disk layout of a project's `.qmd-prover/` state directory: the single
 * source of truth for where each piece of tool state lives. Every reader and
 * writer resolves its paths through here instead of re-joining string literals,
 * so the layout can change in one place.
 */
export function auxLayout(root: string) {
  const graphs = auxPath(root, 'graphs');
  const checks = auxPath(root, 'verification', 'checks');
  return {
    /** The `.qmd-prover/` directory itself. */
    dir: auxPath(root),
    // Authored inputs — tracked by the scaffolded .gitignore.
    config: auxPath(root, 'config.yml'),
    gitignore: auxPath(root, '.gitignore'),
    external: auxPath(root, '.external.qmd'),
    statementLocks: auxPath(root, 'statement-locks.json'),
    // Derived state — regenerated by the tool, ignored by git.
    events: auxPath(root, 'events.jsonl'),
    manifest: auxPath(root, 'manifest.json'),
    graph: auxPath(root, 'graph.json'),
    diagnostics: auxPath(root, 'diagnostics.json'),
    generated: auxPath(root, 'generated'),
    reports: auxPath(root, 'reports'),
    reportStatus: auxPath(root, 'reports', 'status.json'),
    writeLock: auxPath(root, 'write.lock'),
    graphs,
    graphsLatest: path.join(graphs, 'latest.json'),
    snapshot: (snapshotId: string) => path.join(graphs, `${bare(snapshotId)}.json`),
    verification: auxPath(root, 'verification'),
    checks,
    check: (verificationKey: string) => path.join(checks, `${bare(verificationKey)}.json`)
  };
}

const CONFIG_TEMPLATE = [
  `# Comments must be on their own line, not after a value.`,
  ``,
  `project:`,
  `  # exclude: extra path patterns to skip during discovery (.qmd-prover, .git, node_modules,`,
  `  # the render output-dir, and .gitignore entries are always skipped).`,
  `  exclude: [.qmd-prover]`,
  ``,
  `goals:`,
  `  # id-prefix: explicit IDs starting with this become protected main goals — locked statement,`,
  `  # and each must carry both .theorem and .goal.`,
  `  id-prefix: thm-main-`,
  `  protect-statements: true`,
  ``,
  `semantic:`,
  `  # wildcard-imports: when false, use: ['*'] is a WILDCARD_IMPORT error; import each ID by name.`,
  `  wildcard-imports: false`,
  ``,
  `tools:`,
  `  # Optional explicit paths, used when the tool is not on PATH.`,
  `  pandoc: ""`,
  `  quarto: ""`,
  ``,
  `verification:`,
  `  # backend selects the independent verifier: none | claude | codex | command.`,
  `  # none = machine checks only; no proof is ever verified. Set claude or codex to check proofs.`,
  `  backend: none`,
  `  # executable: for claude/codex, path to the CLI (defaults to the backend name on PATH).`,
  `  executable: ""`,
  `  # model: concrete model id forwarded as --model, or "" to let the CLI use its own default.`,
  `  model: ""`,
  `  # effort: reasoning effort forwarded to the backend: low | medium | high | xhigh | max.`,
  `  effort: high`,
  `  # fresh-context: run each check in an isolated context. Changing it re-verifies every fact.`,
  `  fresh-context: true`,
  `  # citations: how strictly an uncited non-standard term is flagged: lenient | standard | strict.`,
  `  citations: standard`,
  `  # rigor: how completely a valid step must be spelled out (strict also makes gaps block): lenient | standard | strict.`,
  `  rigor: standard`,
  `  # tools: capabilities the verifier is TOLD (in the prompt) it may use; any of [file-read, web-search, code].`,
  `  tools: []`,
  ``,
  `render:`,
  `  graph-engine: builtin`,
  `  # output-dir: where render writes generated inputs; created on demand, always excluded.`,
  `  output-dir: .qmd-prover/generated`,
  ``
].join('\n');

const GITIGNORE_TEMPLATE = [
  '# qmd-prover writes derived tool state here. Track only the authored inputs.',
  '/*',
  '!/.gitignore',
  '!/config.yml',
  '!/.external.qmd',
  '!/statement-locks.json',
  ''
].join('\n');

/**
 * Materialize a project's `.qmd-prover/` state directory: write the authored
 * `config.yml` and the state-directory `.gitignore`, each only when absent so a
 * project may customize either. Idempotent, so `init` calls it once up front and
 * every compile calls it again to self-heal a deleted config. Derived subfolders
 * (graphs/, verification/, reports/, …) are created lazily by their own writers,
 * never eagerly here, so nothing stale exists before the first compile or render.
 */
export async function scaffoldAux(root: string): Promise<void> {
  const layout = auxLayout(root);
  if (!await exists(layout.config)) await atomicWrite(layout.config, CONFIG_TEMPLATE);
  await scaffoldAuxGitignore(root);
}

/**
 * Write `.qmd-prover/.gitignore` once, the first time any tool state lands there.
 * It version-controls the authored inputs (config, external basis, statement-lock
 * baseline) and ignores everything qmd-prover regenerates. Never overwritten, so a
 * project may customize it (e.g. share the verifier cache).
 */
export async function scaffoldAuxGitignore(root: string): Promise<void> {
  const file = auxLayout(root).gitignore;
  if (await exists(file)) return;
  await atomicWrite(file, GITIGNORE_TEMPLATE);
}

export async function appendEvent(root: string, event: JsonObject): Promise<void> {
  const file = auxLayout(root).events;
  await mkdir(path.dirname(file), { recursive: true });
  const handle = await open(file, 'a');
  try {
    await handle.write(`${JSON.stringify({ at: new Date().toISOString(), ...event })}\n`);
  } finally {
    await handle.close();
  }
}

export async function withWriteLock<T>(root: string, operation: () => Promise<T>, { timeoutMs = 5000 }: { timeoutMs?: number } = {}): Promise<T> {
  const lock = auxLayout(root).writeLock;
  await mkdir(path.dirname(lock), { recursive: true });
  const started = Date.now();
  while (true) {
    try {
      await mkdir(lock);
      await atomicJson(path.join(lock, 'owner.json'), { pid: process.pid, acquired_at: new Date().toISOString() });
      break;
    } catch (error) {
      if (!hasErrorCode(error, 'EEXIST')) throw error;
      if (Date.now() - started >= timeoutMs) throw new Error(`Timed out waiting for canonical write lock: ${lock}`);
      await new Promise((resolve) => setTimeout(resolve, 40));
    }
  }
  try { return await operation(); } finally { await rm(lock, { recursive: true, force: true }); }
}
