import { mkdir } from 'node:fs/promises';
import path from 'node:path';
import { atomicJson, atomicWrite, AUX } from '../infrastructure/files.js';
import { executableAvailable } from '../infrastructure/executables.js';
import { resolveProjectSnapshot } from '../inspection/snapshot.js';
import { buildProjectInspectionIndex } from '../inspection/index.js';
import { SCHEMA_VERSION } from '../shared/core.js';
import type { Compilation, DependencyGraph, RenderResult, RuntimeOptions } from '../shared/types.js';

function escapeXml(value: unknown = ''): string {
  const entities: Record<string, string> = { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&apos;' };
  return String(value).replace(/[&<>"']/g, (character) => entities[character] ?? character);
}

function graphSvg(graph: DependencyGraph): string {
  const width = 900;
  const row = 78;
  const height = Math.max(120, graph.nodes.length * row + 40);
  const positions = new Map<string, { x: number; y: number }>(graph.nodes.map((node, index) => [node.id, { x: 40 + (index % 2) * 450, y: 30 + index * row }]));
  const edges = graph.edges.map((edge) => {
    const from = positions.get(edge.from); const to = positions.get(edge.to);
    if (!from || !to) return '';
    return `<line x1="${from.x + 180}" y1="${from.y + 24}" x2="${to.x + 180}" y2="${to.y + 24}" stroke="#9aa5b8" stroke-width="1.5"/>`;
  }).join('');
  const nodes = graph.nodes.map((node) => {
    const position = positions.get(node.id);
    if (!position) return '';
    const href = `../../${node.file}#${node.id}`;
    const local = node.local_verification?.outcome ?? node.local_verification?.status ?? 'not-run';
    const global = node.global_verification?.status ?? 'unverified';
    const title = `${node.id}: ${node.title} (local: ${local}; global: ${global})${node.disproof ? ` — ${node.disproof.refutation}` : ''}`;
    return `<a href="${escapeXml(href)}"><g><title>${escapeXml(title)}</title><rect x="${position.x}" y="${position.y}" width="360" height="48" rx="8" fill="#fff" stroke="#64748b"/><text x="${position.x + 12}" y="${position.y + 20}" font-family="sans-serif" font-size="13">${escapeXml(node.id)}</text><text x="${position.x + 12}" y="${position.y + 38}" font-family="sans-serif" font-size="11" fill="#586174">${escapeXml(`local ${local}; global ${global}`)}</text></g></a>`;
  }).join('');
  return `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" role="img" aria-label="Theorem dependency graph">${edges}${nodes}</svg>\n`;
}

function statusQmd(compilation: Compilation): string {
  const tableText = (value: unknown): string => String(value ?? '').replace(/\s+/g, ' ').replace(/\|/g, '\\|').trim();
  const rows = compilation.manifest.results.map((result) => {
    const local = result.local_verification?.outcome ?? result.local_verification?.status ?? 'not-run';
    const global = result.global_verification?.status ?? 'unverified';
    return `| @${result.id} | ${local} | ${global} | ${result.disproof ? `${result.disproof.status}: ${tableText(result.disproof.refutation)}` : '—'} | \`${result.file}:${result.line ?? '?'}\` |`;
  }).join('\n');
  const diagnostics = compilation.diagnostics.length
    ? `\n## Diagnostics\n\n${compilation.diagnostics.map((item) => `- **${item.severity} ${item.code}** in \`${item.file ?? '<project>'}:${item.line ?? '?'}\`: ${item.message}`).join('\n')}\n`
    : '';
  return `---\ntitle: "Proof status"\n---\n\nThis page is generated by qmd-prover from the project's semantic QMD. Local verification is conditional on direct dependency statements; global status is computed from the complete dependency closure.\n\n| Result | Local AI | Global | Refutation evidence | Source |\n|---|---|---|---|---|\n${rows || '| — | — | — | — | — |'}\n\n## Dependency graph\n\n![Proof dependency graph](dependencies.svg){fig-alt="A directed graph from results to the definitions and results cited by their proofs."}\n${diagnostics}`;
}

export async function renderProject(root = process.cwd(), options: RuntimeOptions = {}): Promise<RenderResult> {
  root = path.resolve(root);
  const index = await buildProjectInspectionIndex(root, options);
  const snapshot = await resolveProjectSnapshot(index, options);
  const compilation: Compilation = {
    root,
    config: index.compilation.config,
    manifest: snapshot.manifest,
    graph: snapshot.graph,
    diagnostics: snapshot.diagnostics,
    summary: {
      files: snapshot.manifest.files.length,
      results: snapshot.manifest.results.length,
      errors: snapshot.diagnostics.filter((item) => item.severity === 'error').length,
      warnings: snapshot.diagnostics.filter((item) => item.severity === 'warning').length
    },
    complete: index.compilation.complete,
    ok: snapshot.diagnostics.every((item) => item.severity !== 'error')
  };
  if (!compilation.ok && options.allowErrors !== true) return {
    schema_version: SCHEMA_VERSION,
    operation: 'render',
    ok: false,
    status: 'blocked',
    summary: compilation.summary,
    diagnostics: compilation.diagnostics,
    artifacts_written: false,
    remediation: 'Repair the diagnostics and rerun render, or explicitly use --allow-errors to generate diagnostic artifacts.'
  };
  const output = path.join(root, AUX, 'generated');
  const reportDir = path.join(root, AUX, 'reports');
  await Promise.all([mkdir(output, { recursive: true }), mkdir(reportDir, { recursive: true })]);
  await Promise.all([
    atomicWrite(path.join(output, 'proof-status.qmd'), statusQmd(compilation)),
    atomicWrite(path.join(output, 'dependencies.svg'), graphSvg(compilation.graph)),
    atomicJson(path.join(reportDir, 'status.json'), { summary: compilation.summary, diagnostics: compilation.diagnostics })
  ]);
  const quartoAvailable = await executableAvailable('quarto');
  return {
    schema_version: SCHEMA_VERSION,
    operation: 'render',
    ok: true,
    status: compilation.ok ? 'prepared' : 'prepared-with-errors',
    output: path.relative(root, path.join(output, 'proof-status.qmd')),
    graph_svg: path.relative(root, path.join(output, 'dependencies.svg')),
    report: path.relative(root, path.join(reportDir, 'status.json')),
    ...(quartoAvailable ? { render_command: 'quarto render' } : {}),
    quarto: {
      available: quartoAvailable,
      ...(quartoAvailable ? {} : { remediation: 'Install Quarto before building final HTML, PDF, or other output.' })
    },
    artifacts_written: true,
    artifacts_trustworthy: compilation.ok,
    summary: compilation.summary,
    diagnostics: compilation.diagnostics
  };
}

export { escapeXml, graphSvg, statusQmd };
